// =============================================================
// Pemeran — Stage: Data
// The one fully-working wizard screen for M1. Mapel dropdown is
// loaded from data/mapel.json (owned/generated by another agent);
// if that file isn't there yet (404) or fails to parse, this falls
// back to a free-text mapel field + fully manual JP inputs so the
// screen never blocks a teacher from proceeding.
// =============================================================

import { state, updateHeader, updateConfig, setStage } from '../state.js';
import { toast } from '../api.js';
import { mountOneshotButton } from '../oneshot.js';

let mapelList = null;          // array of raw records from mapel.json, or [] if unavailable
let mapelLoadState = 'idle';   // 'idle' | 'ok' | 'missing' | 'error'

async function loadMapel() {
  if (mapelLoadState !== 'idle') return;
  try {
    const res = await fetch('data/mapel.json', { cache: 'no-store' });
    if (res.status === 404) { mapelLoadState = 'missing'; mapelList = []; return; }
    if (!res.ok) { mapelLoadState = 'error'; mapelList = []; return; }
    const json = await res.json();
    const list = Array.isArray(json) ? json : (json && Array.isArray(json.mapel) ? json.mapel : null);
    if (!list) { mapelLoadState = 'error'; mapelList = []; return; }
    mapelList = list;
    mapelLoadState = 'ok';
  } catch (e) {
    mapelLoadState = 'error';
    mapelList = [];
  }
}

function pick(obj, keys, fallback) {
  for (const k of keys) {
    if (obj && obj[k] !== undefined && obj[k] !== null && obj[k] !== '') return obj[k];
  }
  return fallback;
}
function nameOf(rec) { return pick(rec, ['nama', 'mapel', 'name'], ''); }

// Weeks/year baked into data/mapel.json's own "catatan" (Tabel 6 = kelas 7-8,
// Tabel 7 = kelas 9 of Permendikdasmen 13/2025 Lampiran II) — used only to
// derive a JP/minggu *suggestion* from the regulation's JP/tahun figure; the
// teacher can always override it.
const WEEKS_PER_YEAR = { 7: 36, 8: 36, 9: 32 };

function suggestJpPerMinggu(rec, kelas) {
  if (!rec || !rec.jpPerTahun || !kelas) return null;
  const total = rec.jpPerTahun[String(kelas)];
  const weeks = WEEKS_PER_YEAR[kelas];
  if (!total || !weeks) return null;
  const val = total / weeks;
  return Number.isFinite(val) ? Math.round(val * 100) / 100 : null;
}

function escapeHtml(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}

export async function render(container) {
  await loadMapel();
  const h = state.spine.header;
  const c = state.spine.config;

  container.innerHTML = `
    <div class="stack-lg">
      <div class="card card-pad-lg">
        <h2>Data Perangkat</h2>
        <p class="muted">Lengkapi identitas dasar. Semua bidang bisa diubah lagi nanti.</p>

        <div class="field" id="f-mapel"></div>

        <div class="field">
          <label>Kelas</label>
          <div class="choice-cards" id="kelas-cards">
            ${[7, 8, 9].map((k) => `
              <label class="choice-card${h.kelas === k ? ' is-selected' : ''}" data-kelas="${k}">
                <input type="radio" name="kelas" value="${k}" ${h.kelas === k ? 'checked' : ''}>
                Kelas ${k}
              </label>`).join('')}
          </div>
        </div>

        <div class="field">
          <label for="in-tahun">Tahun Ajaran</label>
          <input type="text" id="in-tahun" placeholder="2026/2027" value="${escapeHtml(h.tahunAjaran)}">
        </div>

        <div class="grid grid-2">
          <div class="field">
            <label for="in-jpminggu">JP / minggu</label>
            <input type="number" id="in-jpminggu" min="1" max="20" value="${c.jpPerMinggu ?? ''}">
          </div>
          <div class="field">
            <label for="in-jppertemuan">JP / pertemuan</label>
            <input type="number" id="in-jppertemuan" min="1" max="10" value="${c.jpPerPertemuan ?? ''}">
          </div>
        </div>

        <div class="field">
          <label for="in-menitperjp">Menit per JP</label>
          <input type="number" id="in-menitperjp" min="20" max="90" step="5" value="${c.menitPerJp ?? 40}">
          <div class="field-hint">sesuai KOSP (umumnya 40 atau 45)</div>
        </div>

        <div class="field">
          <label for="in-totaljp">Total JP / Tahun</label>
          <input type="number" id="in-totaljp" min="1" max="400" value="${c.totalJpTahun ?? ''}">
          <div class="field-hint">Terisi otomatis untuk mapel dengan alokasi resmi/baku — untuk Muatan Lokal tanpa data baku, isi sesuai KOSP. Dipakai ATP untuk menghitung JP per unit.</div>
        </div>

        <div class="field">
          <label for="in-guru">Guru</label>
          <input type="text" id="in-guru" value="${escapeHtml(h.guru)}" readonly>
        </div>
      </div>

      <div id="oneshot-host"></div>

      <div class="row-between">
        <span class="muted small">${escapeHtml(h.sekolah ? h.sekolah + ' · ' + h.kota : '')}</span>
        <button class="btn btn-primary btn-lg" id="btn-next">Simpan &amp; Lanjut →</button>
      </div>
    </div>
  `;

  // ctx carries the currently-selected mapel record across the mapel <select>
  // and the kelas cards, since the JP/minggu suggestion depends on both.
  const ctx = { selectedMapelRec: findMapelByName(h.mapel) };

  renderMapelField(container.querySelector('#f-mapel'), container, ctx);
  wireKelasCards(container, ctx);
  wireSimpleFields(container);
  container.querySelector('#btn-next').addEventListener('click', () => onNext(container));

  // V2a #9: "⚡ Kerangka Instan (tanpa AI)" for every teacher, plus an
  // owner-only "✨ Generate Semuanya dengan AI" button alongside it.
  mountOneshotButton(container.querySelector('#oneshot-host'));
}

function findMapelByName(name) {
  if (!name || mapelLoadState !== 'ok') return null;
  return mapelList.find((m) => nameOf(m) === name) || null;
}

function renderMapelField(el, container, ctx) {
  const h = state.spine.header;

  if (mapelLoadState === 'ok' && mapelList.length) {
    el.innerHTML = `
      <label for="in-mapel">Mata Pelajaran</label>
      <select id="in-mapel">
        <option value="">— pilih mata pelajaran —</option>
        ${mapelList.map((m) => {
          const name = nameOf(m);
          const label = m.mulok ? (name + ' (Muatan Lokal)') : name;
          const sel = ctx.selectedMapelRec && ctx.selectedMapelRec.id === m.id ? 'selected' : '';
          return `<option value="${escapeHtml(m.id)}" ${sel}>${escapeHtml(label)}</option>`;
        }).join('')}
      </select>
      <div class="field-hint" id="mapel-hint"></div>
    `;
    updateMapelHint(container, ctx);
    el.querySelector('#in-mapel').addEventListener('change', (e) => {
      const rec = mapelList.find((m) => m.id === e.target.value) || null;
      ctx.selectedMapelRec = rec;
      updateHeader({ mapel: rec ? nameOf(rec) : '' });
      applyMapelDefaults(container, ctx);
      updateMapelHint(container, ctx);
    });
  } else {
    el.innerHTML = `
      <label for="in-mapel">Mata Pelajaran</label>
      <input type="text" id="in-mapel" placeholder="Ketik nama mata pelajaran" value="${escapeHtml(h.mapel)}">
      <div class="field-hint">Daftar mata pelajaran belum tersedia — isi manual dulu, termasuk JP di bawah.</div>
    `;
    el.querySelector('#in-mapel').addEventListener('input', (e) => updateHeader({ mapel: e.target.value }));
  }
}

function updateMapelHint(container, ctx) {
  const hint = container.querySelector('#mapel-hint');
  if (!hint) return;
  const rec = ctx.selectedMapelRec;
  // Some mulok entries DO carry a school-confirmed jpPerTahun (e.g. ESP —
  // "angka JP dikonfirmasi sekolah" per data/mapel.json's own note) and get
  // auto-filled just like a national mapel below; only genuinely data-less
  // mulok entries (jpPerTahun: null, e.g. "Muatan Lokal lainnya") need the
  // fully-manual warning.
  hint.textContent = rec && rec.mulok && !rec.jpPerTahun
    ? 'Muatan Lokal tanpa data JP baku — isi JP/minggu, JP/pertemuan, dan Total JP/Tahun secara manual (rujuk KOSP).'
    : '';
}

/** Recompute the JP/minggu suggestion + totalJpTahun whenever mapel or kelas changes. */
function applyMapelDefaults(container, ctx) {
  const rec = ctx.selectedMapelRec;
  const kelas = state.spine.header.kelas;
  if (!rec || !rec.jpPerTahun || !kelas) return;
  const total = rec.jpPerTahun[String(kelas)];
  if (total == null) return;
  updateConfig({ totalJpTahun: total });
  const totalInput = container.querySelector('#in-totaljp');
  if (totalInput) totalInput.value = total;
  const perMinggu = suggestJpPerMinggu(rec, kelas);
  if (perMinggu != null) {
    container.querySelector('#in-jpminggu').value = perMinggu;
    updateConfig({ jpPerMinggu: perMinggu });
  }
}

function wireKelasCards(container, ctx) {
  const cards = Array.from(container.querySelectorAll('#kelas-cards .choice-card'));
  cards.forEach((card) => {
    card.addEventListener('click', () => {
      const kelas = Number(card.dataset.kelas);
      cards.forEach((c) => c.classList.remove('is-selected'));
      card.classList.add('is-selected');
      card.querySelector('input').checked = true;
      updateHeader({ kelas });
      applyMapelDefaults(container, ctx);
    });
  });
}

function wireSimpleFields(container) {
  container.querySelector('#in-tahun').addEventListener('input', (e) => updateHeader({ tahunAjaran: e.target.value }));
  container.querySelector('#in-jpminggu').addEventListener('input', (e) => {
    updateConfig({ jpPerMinggu: e.target.value ? Number(e.target.value) : null });
  });
  container.querySelector('#in-jppertemuan').addEventListener('input', (e) => {
    updateConfig({ jpPerPertemuan: e.target.value ? Number(e.target.value) : null });
  });
  container.querySelector('#in-menitperjp').addEventListener('input', (e) => {
    updateConfig({ menitPerJp: e.target.value ? Number(e.target.value) : 40 });
  });
  container.querySelector('#in-totaljp').addEventListener('input', (e) => {
    updateConfig({ totalJpTahun: e.target.value ? Number(e.target.value) : null });
  });
}

async function onNext(container) {
  const h = state.spine.header;
  if (!h.mapel) return toast('Isi mata pelajaran dulu.', { error: true });
  if (!h.kelas) return toast('Pilih kelas dulu.', { error: true });
  if (!h.tahunAjaran) return toast('Isi tahun ajaran dulu.', { error: true });

  const btn = container.querySelector('#btn-next');
  btn.disabled = true;
  btn.textContent = 'Menyimpan…';
  const ok = await setStage('cp');
  btn.disabled = false;
  btn.textContent = 'Simpan & Lanjut →';
  if (ok) {
    location.hash = '#/cp';
  } else if (state.saveStatus !== 'error') {
    // flushSave silently no-op'd (no teacher context to create the plan
    // under) rather than hitting a real API error, which already toasts.
    toast('Tidak bisa menyimpan — sesi guru tidak ditemukan. Kembali ke Beranda dan pilih nama Anda lagi.', { error: true });
  }
}
